pipeline {
    agent {
        label 'server1'
    }
  //as we will explicitylt specify agent on differnt steps
    stages {   //below provided all are sequential stages not parallel
        stage('Build') {
            steps {
                sh 'mvn clean package' 
            }

            post {
            success {
                    archiveArtifacts(artifacts: '**/target/*.war')
                }
            }
        }
        
    }
}
