pipeline {
    agent {
        label 'server1'
    }

    tools {
        maven 'mymaven'
    }

    parameters {
        string defaultValue: 'Panday', name: 'LASTNAME'
    }

    environment {
        Name = "Chetna"
    }
    
  //as we will explicitylt specify agent on differnt steps
    stages {   //below provided all are sequential stages not parallel
        stage('Build') {
            steps {
               // bat 'mvn clean package' 
                echo "$NAME ${params.LASTNAME}"
                }
                }
        stage('Test')
        {
            parallel { 
                stage('TestA')
                {
                    echo "This is Test A"
                }
                stage('TestB')
                {
                    echo "This is Test B"
                }
            }
        }
            }
}
