pipeline {
    agent any

    tools {
        maven 'mymaven'
    }

    parameters {
        string defaultValue: 'Panday', name: 'LASTNAME'
    }

    environment {
        Name = "Chetna"
    }
    
  //as we will explicitylt specify agent on differnt steps
    stages {   //below provided all are sequential stages not parallel
        stage('Build') {
            steps {
                bat 'mvn clean package' 
                bat '%NAME% %{params.LASTNAME}%'
                }
                }
            }

            post {
            success {
                    archiveArtifacts(artifacts: '**/target/*.jar')
                }
            }
     
}
